### ISSUE TITLE
How to use FaceBaker

### ISSUE THREAD

**Issue by enzyme69** [keijiro/FaceBaker#1]
I downloaded the repo, open the project in Unity, but seems to get "compile error". Is there an additional tools or plugins I need to download to use this?

How does the iPhone X connect to Unity?

**Comment by keijiro** [comment]
You have to download ARKit plugin and copy `UnityARKitPlugin` directory to `/Asset/UnityARKitPlugin`. Then you have to launch the Unity ARKit Remote on the phone and connect to the editor.

This is just an experimental project, so please don't expect it works in a practical way.
