### ISSUE TITLE
BlendShapeKey base meshes 

### ISSUE THREAD

**Issue by yosun** [keijiro/FaceBaker#2]
Were you able to bake these to base blend shape key meshes for each blend shape location? 

I notice that you set .AddBlendShapeFrame to 100 each time? Is it possible to perfectly emulate the expression?

**Comment by keijiro** [comment]
The answer might be "yes". Actually I'm not familiar with blend shapes (I was just toying the ideas in this project) so that I can't understand what the point of your problem is. If you find any problem with the blend shape functionality, I'd recommend report it via the bug reporter.
